name: Run main.py daily

on:
  schedule:
    - cron: "0 7 * * *"      # Run every day at 07:00 UTC
  workflow_dispatch:         # Allow manual trigger

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        run: python main.py
